

# ---
# - hosts: G7dev-ws
#   gather_facts: True
#   become: yes

#   vars:
#     source_file: ./index.html
#     dest_file: /var/www/html

#   tasks:
#     - name: Install Apache Web Server for RPM
#       yum:
#         name: httpd
#         state: latest
#       when: ansible_os_family == "RedHat"

#     - name: Install Apache Web Server for Debian
#       apt:
#         name: apache2
#         state: latest
#       when: ansible_os_family == "Debian"

#     - name: Print Linux Family
#       debug:
#         var: ansible_os_family

#     - name: Copy install_httpd.sh for RedHat
#       copy:
#         src: "{{ source_file }}"
#         dest: "{{ dest_file }}"
#         mode: 0555
#       notify: Restart Httpd
#       when: ansible_os_family == "RedHat"

#     - name: Copy install_httpd.sh for Debian
#       copy:
#         src: "{{ source_file }}"
#         dest: "{{ dest_file }}"
#         mode: 0555
#       notify: Restart Apache2
#       when: ansible_os_family == "Debian"

#     - name: Start Apache Web Server for RedHat
#       service:
#         name: httpd
#         state: started
#         enabled: yes
#       when: ansible_os_family == "RedHat"

#     - name: Start Apache Web Server for Debian
#       service:
#         name: apache2
#         state: started
#         enabled: yes
#       when: ansible_os_family == "Debian"

#     - shell: /usr/bin/uptime
#       register: result

#     - name: Print result variable
#       debug:
#         var: result

#     - name: Print debug message
#       debug:
#         msg: "The result was {{ result.stdout }}"

#   handlers:
#     - name: Restart Httpd
#       service:
#         name: httpd
#         state: restarted
#       when: ansible_os_family == "RedHat"

#     - name: Restart Apache2
#       service:
#         name: apache2
#         state: restarted
#       when: ansible_os_family == "Debian"



# - hosts: tag Irina
# gather_facts: True
# become: yes

# vars:
# ansible_user: ec2-user
# ansible_ssh_private_key_file: /home/ec2-user/.ssh/linux
# source_file: ./index.html
# dest_file: /var/www/html
#G7dev-ws
#G7dev-ws
#tag_Group7-ACS730
---
- hosts: G7dev-ws
  gather_facts: True
  become: yes

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ../modules/aws_webservers/Group7
   # ansible_ssh_private_key_file: /home/ec2-user/environment/group7_finalproject/modules/aws_webservers/Group7
    source_file: ./index.html
    dest_file: /var/www/html

  tasks:
    - name: Install Apache Web Server for RPM
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Apache Web Server for Debian
      apt:
        name: apache2
        state: latest
      when: ansible_os_family == "Debian"

    - name: Print Linux Family
      debug:
        var: ansible_os_family

    - name: Copy install_httpd.sh for RedHat
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
        mode: 0555
      notify: Restart Httpd
      when: ansible_os_family == "RedHat"

    - name: Copy install_httpd.sh for Debian
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
        mode: 0555
      notify: Restart Apache2
      when: ansible_os_family == "Debian"

    - name: Start Apache Web Server for RedHat
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start Apache Web Server for Debian
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - shell: /usr/bin/uptime
      register: result

    - name: Print result variable
      debug:
        var: result

    - name: Print debug message
      debug:
        msg: "The result was {{ result.stdout }}"

  handlers:
    - name: Restart Httpd
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == "RedHat"

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"